DROP DATABASE IF EXISTS ESTOQUE_INFORMATICA;
CREATE DATABASE ESTOQUE_INFORMATICA;
USE ESTOQUE_INFORMATICA;


DROP TABLE IF EXISTS TIPO_EQUIPAMENTO;
CREATE TABLE TIPO_EQUIPAMENTO (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS EQUIPAMENTO;
CREATE TABLE EQUIPAMENTO (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	SERIAL VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(50) DEFAULT NULL,
	AQUISICAO VARCHAR(20) DEFAULT NULL,
	FL_DISPONIVEL VARCHAR(1) DEFAULT 'N',
	ID_TIPO_EQUIPAMENTO INT(11) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_TIPO_EQUIPAMENTO) REFERENCES TIPO_EQUIPAMENTO (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS ORDEM_SERVICO;
CREATE TABLE ORDEM_SERVICO (
 	ID INT(11) NOT NULL AUTO_INCREMENT,
 	ORDEM_SERVICO VARCHAR(10) NOT NULL UNIQUE,
 	DATA_ENTRADA DATE NOT NULL,
 	DATA_DEVOLUCAO DATE,
 	ID_EQUIPAMENTO INT(11) NOT NULL,
 	NUM_NF_ENVIO VARCHAR(5),
 	OBSERVACOES TEXT,
 	SERVICOS TEXT,
 	VALOR DECIMAL(15,2) DEFAULT 0,
 	PRIMARY KEY (ID),
 	FOREIGN KEY (ID_EQUIPAMENTO) REFERENCES EQUIPAMENTO (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS DESPACHO_MANUTENCAO;
CREATE TABLE DESPACHO_MANUTENCAO (
 	ID INT(11) NOT NULL AUTO_INCREMENT,
 	DEFEITO TEXT NOT NULL,
  	DATA_SAIDA DATE,
  	ULTIMA_MANUTENCAO VARCHAR(20) DEFAULT NULL,
  	ID_EQUIPAMENTO INT(11) NOT NULL,
  	ID_ORDEM_SERVICO INT(11),
  	PRIMARY KEY (ID),
	FOREIGN KEY (ID_EQUIPAMENTO) REFERENCES EQUIPAMENTO (ID),
	FOREIGN KEY (ID_ORDEM_SERVICO) REFERENCES ORDEM_SERVICO (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS RETORNO_MANUTENCAO;
CREATE TABLE RETORNO_MANUTENCAO (
 	ID INT(11) NOT NULL AUTO_INCREMENT,
 	LAUDO_RETORNO TEXT NOT NULL,
  	DATA_RETORNO DATE,
  	ID_EQUIPAMENTO INT(11) NOT NULL,
  	ID_ORDEM_SERVICO INT(11),
  	PRIMARY KEY (ID),
  	FOREIGN KEY (ID_EQUIPAMENTO) REFERENCES EQUIPAMENTO (ID),
	FOREIGN KEY (ID_ORDEM_SERVICO) REFERENCES ORDEM_SERVICO (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
















