package pojos;
// Generated 06/07/2020 22:00:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DespachoManutencao generated by hbm2java
 */
public class DespachoManutencao  implements java.io.Serializable {


     private Integer id;
     private Equipamento equipamento;
     private OrdemServico ordemServico;
     private String defeito;
     private Date dataSaida;
     private String ultimaManutencao;

    public DespachoManutencao() {
    }

	
    public DespachoManutencao(Equipamento equipamento, String defeito) {
        this.equipamento = equipamento;
        this.defeito = defeito;
    }
    public DespachoManutencao(Equipamento equipamento, OrdemServico ordemServico, String defeito, Date dataSaida, String ultimaManutencao) {
       this.equipamento = equipamento;
       this.ordemServico = ordemServico;
       this.defeito = defeito;
       this.dataSaida = dataSaida;
       this.ultimaManutencao = ultimaManutencao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Equipamento getEquipamento() {
        return this.equipamento;
    }
    
    public void setEquipamento(Equipamento equipamento) {
        this.equipamento = equipamento;
    }
    public OrdemServico getOrdemServico() {
        return this.ordemServico;
    }
    
    public void setOrdemServico(OrdemServico ordemServico) {
        this.ordemServico = ordemServico;
    }
    public String getDefeito() {
        return this.defeito;
    }
    
    public void setDefeito(String defeito) {
        this.defeito = defeito;
    }
    public Date getDataSaida() {
        return this.dataSaida;
    }
    
    public void setDataSaida(Date dataSaida) {
        this.dataSaida = dataSaida;
    }
    public String getUltimaManutencao() {
        return this.ultimaManutencao;
    }
    
    public void setUltimaManutencao(String ultimaManutencao) {
        this.ultimaManutencao = ultimaManutencao;
    }




}


