package pojos;
// Generated 06/07/2020 22:00:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipamento generated by hbm2java
 */
public class Equipamento  implements java.io.Serializable {


     private Integer id;
     private TipoEquipamento tipoEquipamento;
     private String serial;
     private String descricao;
     private String aquisicao;
     private String flDisponivel;
     private Set despachoManutencaos = new HashSet(0);
     private Set retornoManutencaos = new HashSet(0);
     private Set ordemServicos = new HashSet(0);

    public Equipamento() {
    }

	
    public Equipamento(TipoEquipamento tipoEquipamento, String serial) {
        this.tipoEquipamento = tipoEquipamento;
        this.serial = serial;
    }
    public Equipamento(TipoEquipamento tipoEquipamento, String serial, String descricao, String aquisicao, String flDisponivel, Set despachoManutencaos, Set retornoManutencaos, Set ordemServicos) {
       this.tipoEquipamento = tipoEquipamento;
       this.serial = serial;
       this.descricao = descricao;
       this.aquisicao = aquisicao;
       this.flDisponivel = flDisponivel;
       this.despachoManutencaos = despachoManutencaos;
       this.retornoManutencaos = retornoManutencaos;
       this.ordemServicos = ordemServicos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TipoEquipamento getTipoEquipamento() {
        return this.tipoEquipamento;
    }
    
    public void setTipoEquipamento(TipoEquipamento tipoEquipamento) {
        this.tipoEquipamento = tipoEquipamento;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getAquisicao() {
        return this.aquisicao;
    }
    
    public void setAquisicao(String aquisicao) {
        this.aquisicao = aquisicao;
    }
    public String getFlDisponivel() {
        return this.flDisponivel;
    }
    
    public void setFlDisponivel(String flDisponivel) {
        this.flDisponivel = flDisponivel;
    }
    public Set getDespachoManutencaos() {
        return this.despachoManutencaos;
    }
    
    public void setDespachoManutencaos(Set despachoManutencaos) {
        this.despachoManutencaos = despachoManutencaos;
    }
    public Set getRetornoManutencaos() {
        return this.retornoManutencaos;
    }
    
    public void setRetornoManutencaos(Set retornoManutencaos) {
        this.retornoManutencaos = retornoManutencaos;
    }
    public Set getOrdemServicos() {
        return this.ordemServicos;
    }
    
    public void setOrdemServicos(Set ordemServicos) {
        this.ordemServicos = ordemServicos;
    }




}


