package pojos;
// Generated 06/07/2020 22:00:45 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdemServico generated by hbm2java
 */
public class OrdemServico  implements java.io.Serializable {


     private Integer id;
     private Equipamento equipamento;
     private String numOrdemServico;
     private Date dataEntrada;
     private Date dataDevolucao;
     private String numNfEnvio;
     private String observacoes;
     private String servicos;
     private BigDecimal valor;
     private Set despachoManutencaos = new HashSet(0);
     private Set retornoManutencaos = new HashSet(0);

    public OrdemServico() {
    }

	
    public OrdemServico(Equipamento equipamento, String numOrdemServico, Date dataEntrada) {
        this.equipamento = equipamento;
        this.numOrdemServico = numOrdemServico;
        this.dataEntrada = dataEntrada;
    }
    public OrdemServico(Equipamento equipamento, String numOrdemServico, Date dataEntrada, Date dataDevolucao, String numNfEnvio, String observacoes, String servicos, BigDecimal valor, Set despachoManutencaos, Set retornoManutencaos) {
       this.equipamento = equipamento;
       this.numOrdemServico = numOrdemServico;
       this.dataEntrada = dataEntrada;
       this.dataDevolucao = dataDevolucao;
       this.numNfEnvio = numNfEnvio;
       this.observacoes = observacoes;
       this.servicos = servicos;
       this.valor = valor;
       this.despachoManutencaos = despachoManutencaos;
       this.retornoManutencaos = retornoManutencaos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Equipamento getEquipamento() {
        return this.equipamento;
    }
    
    public void setEquipamento(Equipamento equipamento) {
        this.equipamento = equipamento;
    }
    public String getOrdemServico() {
        return this.numOrdemServico;
    }
    
    public void setOrdemServico(String ordemServico) {
        this.numOrdemServico = ordemServico;
    }
    public Date getDataEntrada() {
        return this.dataEntrada;
    }
    
    public void setDataEntrada(Date dataEntrada) {
        this.dataEntrada = dataEntrada;
    }
    public Date getDataDevolucao() {
        return this.dataDevolucao;
    }
    
    public void setDataDevolucao(Date dataDevolucao) {
        this.dataDevolucao = dataDevolucao;
    }
    public String getNumNfEnvio() {
        return this.numNfEnvio;
    }
    
    public void setNumNfEnvio(String numNfEnvio) {
        this.numNfEnvio = numNfEnvio;
    }
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }
    public String getServicos() {
        return this.servicos;
    }
    
    public void setServicos(String servicos) {
        this.servicos = servicos;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Set getDespachoManutencaos() {
        return this.despachoManutencaos;
    }
    
    public void setDespachoManutencaos(Set despachoManutencaos) {
        this.despachoManutencaos = despachoManutencaos;
    }
    public Set getRetornoManutencaos() {
        return this.retornoManutencaos;
    }
    
    public void setRetornoManutencaos(Set retornoManutencaos) {
        this.retornoManutencaos = retornoManutencaos;
    }




}


