package pojos;
// Generated 06/07/2020 22:00:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RetornoManutencao generated by hbm2java
 */
public class RetornoManutencao  implements java.io.Serializable {


     private Integer id;
     private Equipamento equipamento;
     private OrdemServico ordemServico;
     private String laudoRetorno;
     private Date dataRetorno;

    public RetornoManutencao() {
    }

	
    public RetornoManutencao(Equipamento equipamento, String laudoRetorno) {
        this.equipamento = equipamento;
        this.laudoRetorno = laudoRetorno;
    }
    public RetornoManutencao(Equipamento equipamento, OrdemServico ordemServico, String laudoRetorno, Date dataRetorno) {
       this.equipamento = equipamento;
       this.ordemServico = ordemServico;
       this.laudoRetorno = laudoRetorno;
       this.dataRetorno = dataRetorno;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Equipamento getEquipamento() {
        return this.equipamento;
    }
    
    public void setEquipamento(Equipamento equipamento) {
        this.equipamento = equipamento;
    }
    public OrdemServico getOrdemServico() {
        return this.ordemServico;
    }
    
    public void setOrdemServico(OrdemServico ordemServico) {
        this.ordemServico = ordemServico;
    }
    public String getLaudoRetorno() {
        return this.laudoRetorno;
    }
    
    public void setLaudoRetorno(String laudoRetorno) {
        this.laudoRetorno = laudoRetorno;
    }
    public Date getDataRetorno() {
        return this.dataRetorno;
    }
    
    public void setDataRetorno(Date dataRetorno) {
        this.dataRetorno = dataRetorno;
    }




}


