package pojos;
// Generated 21/08/2020 10:14:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoEquipamento generated by hbm2java
 */
public class TipoEquipamento  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set equipamentos = new HashSet(0);

    public TipoEquipamento() {
    }

    public TipoEquipamento(String nome, Set equipamentos) {
       this.nome = nome;
       this.equipamentos = equipamentos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getEquipamentos() {
        return this.equipamentos;
    }
    
    public void setEquipamentos(Set equipamentos) {
        this.equipamentos = equipamentos;
    }




}


